[tools]
rojo = { source = "Roblox/rojo-rbx-rojo", version = "6.2.0" }
selene = { source = "Roblox/Kampfkarren-selene", version = "0.18" }
stylua = { source = "Roblox/JohnnyMorganz-StyLua", version = "0.13" }
luau-analyze = { source = "JohnnyMorganz/luau-analyze-rojo", version = "0.527" }
darklua = { gitlab = "seaofvoices/darklua", version = "0.7.0" }
