[tools]
#luau = { source = "roblox/luau", version = "0.518" }
rojo = { source = "rojo-rbx/rojo", version = "7.0.0" }
selene = { source = "Kampfkarren/selene", version = "0.16" }
stylua = { source = "JohnnyMorganz/StyLua", version = "0.12.5" }
